name: flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android/Destkop/Web, based on GoogleWebRTC.
version: 0.10.6
homepage: https://github.com/cloudwebrtc/flutter-webrtc
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=1.22.0'

dependencies:
  collection: ^1.18.0
  dart_webrtc: ^1.4.5
  flutter:
    sdk: flutter
  path_provider: 2.1.3
  web: ^0.5.1
  webrtc_interface: ^1.2.0
  equatable: ^2.0.5
  rxdart: ^0.27.7
  async: ^2.11.0
  freezed_annotation: any
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lints: ^4.0.0
  build_runner: any
  freezed: any
  json_serializable: ^6.8.0
  pedantic: ^1.11.1
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
      windows:
        pluginClass: FlutterWebRTCPlugin
      linux:
        pluginClass: FlutterWebRTCPlugin