name: flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android/Destkop/Web, based on GoogleWebRTC.
version: 0.12.3
homepage: https://github.com/cloudwebrtc/flutter-webrtc
publish_to: none
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=1.22.0'

dependencies:
  collection: ^1.18.0
  dart_webrtc:
    git:
      url: git@github.com:pam3ec555/dart-webrtc.git
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  web: ^1.0.0
  webrtc_interface: ^1.2.0
  equatable: ^2.0.5
  rxdart: ^0.28.0
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lints: ^4.0.0
  pedantic: ^1.11.1
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
      windows:
        pluginClass: FlutterWebRTCPlugin
      linux:
        pluginClass: FlutterWebRTCPlugin
      elinux:
        pluginClass: FlutterWebRTCPlugin